<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ $fileName }}</title>
<style>
table.customTable {
  width: 100%;
  background-color: #FFFFFF;
  border-collapse: collapse;
  border-width: 2px;
  border-color: #7EA8F8;
  border-style: solid;
  color: #000000;
}

table.customTable td, table.customTable th {
  border-width: 2px;
  border-color: #7EA8F8;
  border-style: solid;
  padding: 5px;
}

table.customTable thead {
  background-color: #7EA8F8;
}
span.centerImage {
     text-align: center;
}
</style>
  </head>
  <body>
    <center><img src="{{ $img }}"/>
    <h2>Mini Statement Receipt</h2>
    </center><br />
    <table class="customTable">
    <thead>
        <tr>
            @foreach($tableHead as $i => $head)
                <th>{{ $head }}</th>
            @endforeach
        </tr>
    </thead>
      <tbody>
      @foreach($tableBody as $index => $report)
            <tr align="center">
                <td>{{ $index+1 }}</td>
                <td>{{ $report['date'] }}</td>
                <td>{{ $report['txnType'] }}</td>
                <td>Rs. {{ $report['amount'] }}</td>
                <td>{{ $report['narration'] }}</td>
            </tr>
        @endforeach
      </tbody>
      <br /> <br />
    </table>
    <table class="customTable">
        <caption style="font-size:140%">Additional Details</caption>
        <tbody>
            @foreach($footer as $key=>$value)
            <tr align="center">
                <td>{{ $key }}</td>
                <td>{{ $value }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <br /><br />
    <center>*** This statement is generated by PayMama Merchant with consent of the Account Holder***</center>
  </body>
</html>
